### ISSUE TITLE
Admin areas that have been dissolved are not ignored

### ISSUE THREAD

**Issue by alexsdutton** [everypolitician/commons-builder#73]
For example, our [executive index query](http://tinyurl.com/ybmw2j4p) for India returns results for Province of East Punjab, which was dissolved, and whose inclusion leads to unnecessary warnings.

**Comment by ostephens** [comment]
Note that there is a current state of Punjab in India Q22424. 
The dissolved state of Punjab is Q2354639

The legislative index query only finds the current state Q22424 because Q2354639 has no attached legislature

However the [executive index query](http://tinyurl.com/ybmw2j4p) finds both

**Comment by alexsdutton** [comment]
Yes, I think I got confused, and have now updated the description to say the executive index query is the better example :-)
