### ISSUE TITLE
Italian senators for life result in an additional legislative/index.json entry

### ISSUE THREAD

**Issue by alexsdutton** [everypolitician/commons-builder#87]
Italy's senate (https://www.wikidata.org/wiki/Q633872) has two `has part`s, "member of the Italian senate" (https://www.wikidata.org/wiki/Q13653224) and "senatore a vita (senator for life)" (https://www.wikidata.org/wiki/Q826589), with the latter a subclass of the former. This means two entries in `legislative/index.json` at the moment, which is Bad. I think we want to exclude the latter, and then update the legislative membership query to also consider subclasses of the specific position item.

**Comment by jacksonj04** [comment]
See also Pakistan, where the Chair of the Senate is a subclass of Senator and similarly causes two entries.
